config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :bookmarks, except: [:index]
  end
  get 'about' => 'welcome#about'

  resources :title, only: [:edit, :destroy]
  devise_for :users
  root 'topics#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def show
    @bookmark = @topic.bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end
  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.new(bookmark_params)

    if @bookmark.save
      flash[:notice] = "Bookmark was saved"
      redirect_to @topic
    else

      flash.now[:alert] = "There was and error saving the bookmark. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.destroy
      flash[:notice] = "Bookmark was deleted"
       redirect_to @topic
    else

      flash.now[:alert] = "There was and error Deleting the bookmark. Please try again."
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end
  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)

    if @bookmark.save
      flash[:notice] = "Bookmark was updated successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "There was an error saving the Bookmark. Please try again."
      render :edit
    end
  end
end

private

def bookmark_params
    params.require(:bookmark).permit(:url, :topic_id)
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
  end

  def create
     @topic = Topic.new
     @topic.title = params[:topic][:title]

     if @topic.save
       flash[:notice] = "Topic was saved successfully."
       redirect_to @topic
     else
       flash.now[:alert] = "There was an error saving the topic. Please try again."
       render :new
     end
   end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
     @topic = Topic.find(params[:id])
     @topic.title = params[:topic][:title]

     if @topic.save
       flash[:notice] = "Topic was updated successfully."
       redirect_to @topic
     else
       flash.now[:alert] = "There was an error saving the topic. Please try again."
       render :edit
     end
   end

   def destroy
     @topic = Topic.find(params[:id])

     if @topic.destroy
       flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
       redirect_to topics_path
     else
       flash[:error] = "There was an error deleting the topic."
       render :show
     end
  end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>

<div class="row">
 <div class="col-md-4">
   <p>Guidelines for Bookmarks</p>
   <ul>
     <li>Make sure it is spelled correctly.</li>
     <li>Make sure it has HTTP before the link</li>
   </ul>
 </div>
 <div class="col-md-8">
   <%= form_for [@topic, @bookmark] do |f| %>
     <div class="form-group">
       <%= f.label :url %>
       <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url" %>
     </div>
     <div class="form-group">
       <%= f.submit "Save", class: 'btn btn-success' %>
     </div>
   <% end %>
 </div>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<div class="row">
 <div class="col-md-4">
   <p>Guidelines for Bookmarks</p>
   <ul>
     <li>Make sure it is spelled correctly.</li>
     <li>Make sure it has HTTP before the link</li>
   </ul>
 </div>
 <div class="col-md-8">
   <%= form_for [@topic, @bookmark] do |f| %>
     <div class="form-group">
       <%= f.label :url %>
       <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url" %>
     </div>
     <div class="form-group">
       <%= f.submit "Save", class: 'btn btn-success' %>
     </div>
   <% end %>
 </div>
</div>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarkapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
   Signed in as: <strong><%= current_user.email %></strong> |
   <%= link_to 'My Blocmarks', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
<%= yield %>

</body>
</html>

app/views/topics/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
 <div class="col-md-4">
   <p>Guidelines for Topics</p>
   <ul>
     <li>Make sure it is spelled correctly.</li>
   </ul>
 </div>
 <div class="col-md-8">
   <%= form_for @topic do |f| %>
     <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
     </div>
     <div class="form-group">
       <%= f.submit "Save", class: 'btn btn-success' %>
     </div>
   <% end %>
 </div>
</div>

app/views/topics/index.html.erb
<div align="center">
  <h1>All Blocmarks</h1>
</div>
<div align="center">
  <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
</div>
<div class="row">
  <div class="col-md-12" align="center">
    <% @topics.each do |topic| %>
    <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.title, topic_path(topic.id) %>
            <%= link_to "Delete", topic_path(topic, topic.id), method: :delete, class: 'glyphicon', data: {confirm: 'Are you sure you want to delete this topic?'} %>
            <% end %>
          </h4>
        </div>
      </div>
  </div>
 </div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
 <div class="col-md-4">
   <p>Guidelines for topics</p>
   <ul>
     <li>Make sure it is spelled correctly.</li>
   </ul>
 </div>
 <div class="col-md-8">
   <%= form_for @topic do |f| %>
     <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: 'form-control', placeholder: "Enter Topic title" %>
     </div>
     <div class="form-group">
       <%= f.submit "Save", class: 'btn btn-success' %>
     </div>
   <% end %>
 </div>
</div>

app/views/topics/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= @topic.title %></h1>
  </div>
  <div class="col-md-12">
    <%= link_to "Edit", edit_topic_path(@topic), class: 'btn btn-success' %>
    <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this topic?'} %>
  </div>
</div>
<h1>Your Bookmarks</h1>
<% @bookmarks.each do |bookmark| %>
  <p><a href="<%= bookmark.url %>"><%= bookmark.url %></a> <%= link_to "Edit", edit_topic_bookmark_path(@topic, bookmark), class: 'glyphicon' %> <%= link_to "Delete", topic_bookmark_path(@topic, bookmark), method: :delete, class: 'glyphicon', data: {confirm: 'Are you sure you want to delete this bookmark?'} %></p>
<% end %>
<div class="row" align="center">
    <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
  </div>

app/views/welcome/about.html.erb
<h1>About BOOKMARK</h1>
<p>Quality social bookmarking app that allows users to send, manage, and share bookmarks</p>

app/views/welcome/index.html.erb
<h1>BOOKMARK</h1>